# User Settings | Edit there as per required

title: ehrenbeck
url: "www.ehrenbeck.me"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    ehrenbeck 

email: behrenbe@hawk.iit.edu
author: Blake Ehrenbeck
# This description will show up in google search results
# (for index page) etc.
description: >
    Blake Ehrenbeck

# This will what will show against &copy; in the footer
copyright: Blake Ehrenbeck
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    I'm a Senior at the Illinois Institute of Technology, starting to look for roles in the tech industry. 
    I'm particularly interested in Artificial Intelligence and Data Analytics. In addition to working on a B.S. in Computer Science, 
    I am pursuing a specialization in Data Science.

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Keep this sentence less than 13 words or it won't look good.

about_footer: true

github_username: ehrenbeck

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID


####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
